FROM openjdk:17-oracle

# RUN apk update && apk add --no-cache tzdata

# Set timezone
RUN rm -f /etc/localtime
RUN ln -s /usr/share/zoneinfo/Africa/Douala /etc/localtime
RUN "date"

ENV TEESE_DATASOURCE_HOST=${TEESE_DATASOURCE_HOST}
ENV TEESE_DATASOURCE_DB_NAME=${TEESE_DATASOURCE_DB_NAME}
ENV TEESE_DATASOURCE_PORT=${TEESE_DATASOURCE_PORT}
ENV TEESE_DATASOURCE_USERNAME=${TEESE_DATASOURCE_USERNAME}
ENV TEESE_DATASOURCE_PASSWORD=${TEESE_DATASOURCE_PASSWORD}
ENV TEESE_EMAIL_HOST=${TEESE_EMAIL_HOST}
ENV TEESE_EMAIL_USERNAME=${TEESE_EMAIL_USERNAME}
ENV TEESE_EMAIL_PASSWORD=${TEESE_EMAIL_PASSWORD}
ENV TEESE_EMAIL_PORT=${TEESE_EMAIL_PORT}
ENV TEESE_SITE_PREFIX=${TEESE_SITE_PREFIX}
ENV TEESE_STORAGE_LOCATION=${TEESE_STORAGE_LOCATION}

# RUN apk add --update ttf-dejavu && rm -rf /var/cache/apk/*

ADD target/Suivie_requetes-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

EXPOSE 8080
